/* file chinh sua ,,.*/


ALTER TABLE BANGCONG WITH CHECK ADD  CONSTRAINT FK_BANGCONG_LOAICONG FOREIGN KEY(IDLC)
REFERENCES LOAICONG (IDLC)
GO

-- noi phan cong voi cac loai phan cong -- 
ALTER TABLE BANGCONG CHECK CONSTRAINT FK_BANGCONG_LOAICONG
GO
ALTER TABLE BANGCONG  WITH CHECK ADD  CONSTRAINT FK_BANGCONG_NHANVIEN FOREIGN KEY(MANV)
REFERENCES NHANVIEN (MANV)
GO

-- nhan vien
ALTER TABLE BANGCONG CHECK CONSTRAINT FK_BANGCONG_NHANVIEN
GO
ALTER TABLE BANGCONG DROP CONSTRAINT FK_BANGCONG_LOAICONG
GO
ALTER TABLE BAOHIEM  WITH CHECK ADD  CONSTRAINT FK_BAOHIEM_NHANVIEN FOREIGN KEY(MANV)
REFERENCES NHANVIEN (MANV)
GO

--Xoa lai bang

DROP TABLE PHONGBAN
GO

CREATE TABLE PHONGBAN(
	IDPB int IDENTITY(1,1) NOT NULL,
	TENPB nvarchar(50) NULL,
	FOREIGN KEY(IDPB) REFERENCES CLUSTERED(IDPB)
)
GO

ALTER TABLE NHANVIEN
ADD HINHANH varbinary(max) NULL
GO

ALTER TABLE NHANVIEN_DIEUCHUYEN
ADD LYDO nvarchar(300) NULL
GO

ALTER TABLE NHANVIEN_NANGLUONG
ADD HESOLUONGMOI float NULL
GO

ALTER TABLE TAIKHOAN
ADD PASSWD varchar(50) NULL
GO

-- export 
ALTER TABLE NHANVIEN CHECK CONSTRAINT FK_NHANVIEN_TONGIAO
GO
ALTER TABLE NHANVIEN  WITH CHECK ADD  CONSTRAINT FK_NHANVIEN_TRINHDO FOREIGN KEY(IDTD)
REFERENCES TRINHDO (IDTD)
GO
ALTER TABLE NHANVIEN CHECK CONSTRAINT FK_NHANVIEN_TRINHDO
GO