USE [master]
GO
/****** Object:  Database [HTTT]    Script Date: 12/30/2022 1:47:56 PM ******/
CREATE DATABASE [HTTT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HTTT1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HTTT1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HTTT1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HTTT1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [HTTT] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HTTT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HTTT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HTTT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HTTT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HTTT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HTTT] SET ARITHABORT OFF 
GO
ALTER DATABASE [HTTT] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HTTT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HTTT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HTTT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HTTT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HTTT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HTTT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HTTT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HTTT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HTTT] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HTTT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HTTT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HTTT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HTTT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HTTT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HTTT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HTTT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HTTT] SET RECOVERY FULL 
GO
ALTER DATABASE [HTTT] SET  MULTI_USER 
GO
ALTER DATABASE [HTTT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HTTT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HTTT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HTTT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HTTT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [HTTT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [HTTT] SET QUERY_STORE = OFF
GO
USE [HTTT]
GO
/****** Object:  Table [dbo].[CanBo]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CanBo](
	[MaCB] [int] NOT NULL,
	[HoTen] [nvarchar](100) NULL,
	[CapBac] [nvarchar](50) NULL,
	[ChucVu] [nvarchar](50) NULL,
	[PhienHieuDonVi] [varchar](50) NULL,
	[MaTK] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaCB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CapDonVi]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CapDonVi](
	[MaCap] [int] NOT NULL,
	[TenCap] [nvarchar](50) NULL,
 CONSTRAINT [PK_CapDonVi] PRIMARY KEY CLUSTERED 
(
	[MaCap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DonVi]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DonVi](
	[PhienHieuDonVi] [varchar](50) NOT NULL,
	[TenDonVi] [nvarchar](50) NULL,
	[MaCap] [int] NULL,
 CONSTRAINT [PK_DonVi] PRIMARY KEY CLUSTERED 
(
	[PhienHieuDonVi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HocVien]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HocVien](
	[MaHV] [int] NOT NULL,
	[TenHV] [nvarchar](50) NULL,
	[PhienHieuDonVi] [varchar](50) NULL,
	[CapBac] [nvarchar](50) NULL,
	[MaTK] [int] NULL,
 CONSTRAINT [PK_HocVien] PRIMARY KEY CLUSTERED 
(
	[MaHV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KeHoachCongTac]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KeHoachCongTac](
	[MaKH] [int] IDENTITY(1,1) NOT NULL,
	[NoiDungKH] [nvarchar](max) NULL,
	[DiaDiem] [nvarchar](200) NULL,
	[MaTrucBan] [int] NULL,
	[MaChiHuy] [int] NULL,
	[PhienHieuDonVi] [varchar](50) NULL,
	[TPThucHien] [nvarchar](200) NULL,
	[PheDuyet] [int] NULL,
	[HoanThanh] [int] NULL,
	[ThoiGian] [date] NULL,
	[TrangThai] [nvarchar](200) NULL,
 CONSTRAINT [PK_KeHoachCongTac] PRIMARY KEY CLUSTERED 
(
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhanXetKeHoach]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhanXetKeHoach](
	[MaNXKH] [int] NOT NULL,
	[MaKH] [int] NULL,
	[MaCB] [int] NULL,
	[NhanXet] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNXKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhanXetNhatKy]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhanXetNhatKy](
	[MaNXNK] [int] NOT NULL,
	[MaNK] [int] NULL,
	[MaCB] [int] NULL,
	[NhanXet] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNXNK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhatKyCongViec]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhatKyCongViec](
	[MaNK] [int] NOT NULL,
	[HoanThanh] [int] NULL,
	[TrangThai] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PhanCong]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PhanCong](
	[MaHV] [int] NOT NULL,
	[MaKH] [int] NOT NULL,
	[NoiDungCV] [nvarchar](max) NULL,
	[HoanThanh] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaHV] ASC,
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO