USE [master]
GO
/****** Object:  Database [HTTT]    Script Date: 12/30/2022 1:47:56 PM ******/
CREATE DATABASE [HTTT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HTTT1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HTTT1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HTTT1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HTTT1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [HTTT] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HTTT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HTTT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HTTT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HTTT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HTTT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HTTT] SET ARITHABORT OFF 
GO
ALTER DATABASE [HTTT] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HTTT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HTTT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HTTT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HTTT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HTTT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HTTT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HTTT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HTTT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HTTT] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HTTT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HTTT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HTTT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HTTT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HTTT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HTTT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HTTT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HTTT] SET RECOVERY FULL 
GO
ALTER DATABASE [HTTT] SET  MULTI_USER 
GO
ALTER DATABASE [HTTT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HTTT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HTTT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HTTT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HTTT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [HTTT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [HTTT] SET QUERY_STORE = OFF
GO
USE [HTTT]
GO
/****** Object:  Table [dbo].[CanBo]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CanBo](
	[MaCB] [int] NOT NULL,
	[HoTen] [nvarchar](100) NULL,
	[CapBac] [nvarchar](50) NULL,
	[ChucVu] [nvarchar](50) NULL,
	[PhienHieuDonVi] [varchar](50) NULL,
	[MaTK] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaCB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CapDonVi]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CapDonVi](
	[MaCap] [int] NOT NULL,
	[TenCap] [nvarchar](50) NULL,
 CONSTRAINT [PK_CapDonVi] PRIMARY KEY CLUSTERED 
(
	[MaCap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DonVi]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DonVi](
	[PhienHieuDonVi] [varchar](50) NOT NULL,
	[TenDonVi] [nvarchar](50) NULL,
	[MaCap] [int] NULL,
 CONSTRAINT [PK_DonVi] PRIMARY KEY CLUSTERED 
(
	[PhienHieuDonVi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HocVien]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HocVien](
	[MaHV] [int] NOT NULL,
	[TenHV] [nvarchar](50) NULL,
	[PhienHieuDonVi] [varchar](50) NULL,
	[CapBac] [nvarchar](50) NULL,
	[MaTK] [int] NULL,
 CONSTRAINT [PK_HocVien] PRIMARY KEY CLUSTERED 
(
	[MaHV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KeHoachCongTac]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KeHoachCongTac](
	[MaKH] [int] IDENTITY(1,1) NOT NULL,
	[NoiDungKH] [nvarchar](max) NULL,
	[DiaDiem] [nvarchar](200) NULL,
	[MaTrucBan] [int] NULL,
	[MaChiHuy] [int] NULL,
	[PhienHieuDonVi] [varchar](50) NULL,
	[TPThucHien] [nvarchar](200) NULL,
	[PheDuyet] [int] NULL,
	[HoanThanh] [int] NULL,
	[ThoiGian] [date] NULL,
	[TrangThai] [nvarchar](200) NULL,
 CONSTRAINT [PK_KeHoachCongTac] PRIMARY KEY CLUSTERED 
(
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhanXetKeHoach]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhanXetKeHoach](
	[MaNXKH] [int] NOT NULL,
	[MaKH] [int] NULL,
	[MaCB] [int] NULL,
	[NhanXet] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNXKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhanXetNhatKy]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhanXetNhatKy](
	[MaNXNK] [int] NOT NULL,
	[MaNK] [int] NULL,
	[MaCB] [int] NULL,
	[NhanXet] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNXNK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhatKyCongViec]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhatKyCongViec](
	[MaNK] [int] NOT NULL,
	[HoanThanh] [int] NULL,
	[TrangThai] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PhanCong]    Script Date: 12/30/2022 1:47:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PhanCong](
	[MaHV] [int] NOT NULL,
	[MaKH] [int] NOT NULL,
	[NoiDungCV] [nvarchar](max) NULL,
	[HoanThanh] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaHV] ASC,
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[tb_BANGCONG](
	[MABC] [int] IDENTITY(1,1) NOT NULL,
	[NAM] [int] NULL,
	[THANG] [int] NULL,
	[NGAY] [int] NULL,
	[GIOVAO] [int] NULL,
	[PHUTVAO] [int] NULL,
	[GIORA] [int] NULL,
	[PHUTRA] [int] NULL,
	[MANV] [int] NULL,
	[IDLC] [int] NULL,
 CONSTRAINT [PK__BANGCONG__603FFF88AE52B9C8] PRIMARY KEY CLUSTERED 
(
	[MABC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_BANGCONG_NV_CT]    Script Date: 1/1/2023 7:09:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_BANGCONG_NV_CT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MAKYCONG] [int] NULL,
	[MACTY] [int] NULL,
	[MANV] [int] NULL,
	[HOTEN] [nvarchar](50) NULL,
	[NGAY] [datetime] NULL,
	[THU] [nvarchar](50) NULL,
	[GIOVAO] [nvarchar](50) NULL,
	[GIORA] [nvarchar](50) NULL,
	[NGAYPHEP] [float] NULL,
	[NGAYCONG] [float] NULL,
	[NGHIKHONGPHEP] [float] NULL,
	[CONGNGAYLE] [float] NULL,
	[CONGCHUNHAT] [float] NULL,
	[KYHIEU] [nvarchar](50) NULL,
	[GHICHU] [nvarchar](500) NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [int] NULL,
	[UPDATED_DATE] [datetime] NULL,
 CONSTRAINT [PK_BANGCONG_NHANVIEN_CT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_BANGLUONG]    Script Date: 1/1/2023 7:09:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_BANGLUONG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MAKYCONG] [int] NULL,
	[MANV] [int] NULL,
	[HOTEN] [nvarchar](50) NULL,
	[NGAYCONGTRONGTHANG] [int] NULL,
	[NGAYPHEP] [float] NULL,
	[KHONGPHEP] [float] NULL,
	[NGAYLE] [float] NULL,
	[NGAYCHUNHAT] [float] NULL,
	[NGAYTHUONG] [float] NULL,
	[TANGCA] [float] NULL,
	[PHUCAP] [float] NULL,
	[UNGLUONG] [float] NULL,
	[THUCLANH] [float] NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [int] NULL,
	[UPDATED_DATE] [datetime] NULL,
 CONSTRAINT [PK__tb_BANGL__3214EC277A84364E] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_BAOCAO]    Script Date: 1/1/2023 7:09:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_BAOCAO](
	[REP_CODE] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[REP_NAME] [nvarchar](100) NULL,
	[VISIBLED] [bit] NULL,
	[TUNGAY] [bit] NULL,
	[THANGNAM] [bit] NULL,
	[IDPB] [bit] NULL,
	[IDBP] [bit] NULL,
	[IDCV] [bit] NULL,
 CONSTRAINT [PK__BAOCAO__49CFF94910383DA9] PRIMARY KEY CLUSTERED 
(
	[REP_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_BAOHIEM]    Script Date: 1/1/2023 7:09:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_BAOHIEM](
	[SOQUYETDINH] [nvarchar](50) NOT NULL,
	[NGAYCAP] [datetime] NULL,
	[NOICAP] [nvarchar](200) NULL,
	[NOIKHAMBENH] [nvarchar](200) NULL,
	[MANV] [int] NULL,
	[LOAI] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [int] NULL,
	[UPDATED_DATE] [datetime] NULL,
 CONSTRAINT [PK__BAOHIEM__B87DA8DFF354743C] PRIMARY KEY CLUSTERED 
(
	[SOQUYETDINH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_BOPHAN]    Script Date: 1/1/2023 7:09:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_BOPHAN](
	[IDBP] [int] IDENTITY(1,1) NOT NULL,
	[TENBP] [nvarchar](50) NULL,
	[MACTY] [int] NULL,
 CONSTRAINT [PK__BOPHAN__B87DA8D7EAC4119C] PRIMARY KEY CLUSTERED 
(
	[IDBP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_CHUCNANG]    Script Date: 1/1/2023 7:09:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_CHUCNANG](
	[FUNC_CODE] [varchar](50) NOT NULL,
	[SORT] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](200) NULL,
	[ISGROUP] [bit] NULL,
	[PARENT] [varchar](50) NULL,
	[MENU] [bit] NULL,
	[TIPS] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[FUNC_CODE] ASC,
	[SORT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_CHUCVU]    Script Date: 1/1/2023 7:09:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_CHUCVU](
	[IDCV] [int] IDENTITY(1,1) NOT NULL,
	[TENCV] [nvarchar](50) NULL,
 CONSTRAINT [PK__CHUCVU__B87D808B068BE3E3] PRIMARY KEY CLUSTERED 
(
	[IDCV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_CONFIG]    Script Date: 1/1/2023 7:09:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_CONFIG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NULL,
	[VALUE] [nvarchar](50) NULL,
 CONSTRAINT [PK__tb_CONFI__3214EC274CDCA580] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_CONGTY]    Script Date: 1/1/2023 7:09:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_CONGTY](
	[MACTY] [int] IDENTITY(1,1) NOT NULL,
	[TENCTY] [nvarchar](100) NULL,
	[DIENTHOAI] [nvarchar](15) NULL,
	[EMAIL] [nvarchar](100) NULL,
	[DIACHI] [nvarchar](200) NULL,
 CONSTRAINT [PK__tb_CONGT__788BBDFD476D3FAB] PRIMARY KEY CLUSTERED 
(
	[MACTY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tb_DANTOC]    Script Date: 1/1/2023 7:09:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb_DANTOC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TENDT] [nvarchar](50) NULL,
 CONSTRAINT [PK__DANTOC__3214EC27921B6FA1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO