//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNHANSUEntities : DbContext
    {
        public QLNHANSUEntities()
            : base("name=QLNHANSUEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<tb_BANGCONG> tb_BANGCONG { get; set; }
        public virtual DbSet<tb_BAOCAO> tb_BAOCAO { get; set; }
        public virtual DbSet<tb_CONGTY> tb_CONGTY { get; set; }
        public virtual DbSet<tb_CHUCNANG> tb_CHUCNANG { get; set; }
        public virtual DbSet<tb_CHUCVU> tb_CHUCVU { get; set; }
        public virtual DbSet<tb_DANTOC> tb_DANTOC { get; set; }
        public virtual DbSet<tb_KYCONGCHITIET> tb_KYCONGCHITIET { get; set; }
        public virtual DbSet<tb_KYLUAT> tb_KYLUAT { get; set; }
        public virtual DbSet<tb_KHENTHUONG> tb_KHENTHUONG { get; set; }
        public virtual DbSet<tb_LOAICA> tb_LOAICA { get; set; }
        public virtual DbSet<tb_LOAICONG> tb_LOAICONG { get; set; }
        public virtual DbSet<tb_NHANVIEN> tb_NHANVIEN { get; set; }
        public virtual DbSet<tb_NHANVIEN_DIEUCHUYEN> tb_NHANVIEN_DIEUCHUYEN { get; set; }
        public virtual DbSet<tb_NHANVIEN_THOIVIEC> tb_NHANVIEN_THOIVIEC { get; set; }
        public virtual DbSet<tb_NHOM> tb_NHOM { get; set; }
        public virtual DbSet<tb_PHONGBAN> tb_PHONGBAN { get; set; }
        public virtual DbSet<tb_PHUCAP> tb_PHUCAP { get; set; }
        public virtual DbSet<tb_TONGIAO> tb_TONGIAO { get; set; }
        public virtual DbSet<tb_TRINHDO> tb_TRINHDO { get; set; }
        public virtual DbSet<tb_KYCONG> tb_KYCONG { get; set; }
        public virtual DbSet<tb_BANGCONG_NV_CT> tb_BANGCONG_NV_CT { get; set; }
        public virtual DbSet<tb_NHANVIEN_PHUCAP> tb_NHANVIEN_PHUCAP { get; set; }
        public virtual DbSet<tb_TANGCA> tb_TANGCA { get; set; }
        public virtual DbSet<tb_CONFIG> tb_CONFIG { get; set; }
        public virtual DbSet<tb_UNGLUONG> tb_UNGLUONG { get; set; }
        public virtual DbSet<tb_BANGLUONG> tb_BANGLUONG { get; set; }
        public virtual DbSet<tb_HOPDONG> tb_HOPDONG { get; set; }
        public virtual DbSet<tb_NHANVIEN_NANGLUONG> tb_NHANVIEN_NANGLUONG { get; set; }
        public virtual DbSet<tb_TAIKHOAN> tb_TAIKHOAN { get; set; }
        public virtual DbSet<tb_QUYEN> tb_QUYEN { get; set; }
        public virtual DbSet<tb_QUYENBAOCAO> tb_QUYENBAOCAO { get; set; }
        public virtual DbSet<tb_BOPHAN> tb_BOPHAN { get; set; }
        public virtual DbSet<tb_BAOHIEM> tb_BAOHIEM { get; set; }
    }
}
