//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BANGLUONG
    {
        public int ID { get; set; }
        public Nullable<int> MAKYCONG { get; set; }
        public Nullable<int> MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<int> NGAYCONGTRONGTHANG { get; set; }
        public Nullable<double> NGAYPHEP { get; set; }
        public Nullable<double> KHONGPHEP { get; set; }
        public Nullable<double> NGAYLE { get; set; }
        public Nullable<double> NGAYCHUNHAT { get; set; }
        public Nullable<double> NGAYTHUONG { get; set; }
        public Nullable<double> TANGCA { get; set; }
        public Nullable<double> PHUCAP { get; set; }
        public Nullable<double> UNGLUONG { get; set; }
        public Nullable<double> THUCLANH { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
