//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BAOCAO
    {
        public int REP_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string REP_NAME { get; set; }
        public Nullable<bool> VISIBLED { get; set; }
        public Nullable<bool> TUNGAY { get; set; }
        public Nullable<bool> THANGNAM { get; set; }
        public Nullable<bool> IDPB { get; set; }
        public Nullable<bool> IDBP { get; set; }
        public Nullable<bool> IDCV { get; set; }
    }
}
