//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BANGCONG
    {
        public int MABC { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<int> NGAY { get; set; }
        public Nullable<int> GIOVAO { get; set; }
        public Nullable<int> PHUTVAO { get; set; }
        public Nullable<int> GIORA { get; set; }
        public Nullable<int> PHUTRA { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<int> IDLC { get; set; }
    
        public virtual tb_LOAICONG tb_LOAICONG { get; set; }
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
    }
}
