//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CHUCNANG
    {
        public string FUNC_CODE { get; set; }
        public int SORT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> ISGROUP { get; set; }
        public string PARENT { get; set; }
        public Nullable<bool> MENU { get; set; }
        public string TIPS { get; set; }
    }
}
